[package]
name = "cryptopals"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
rand = "0.8.5"
aes = "0.8.2"
indicatif = "0.17.3"
rug = "1.19.0"