[package]
name = "cryptopals"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
rand = "0.8"
aes = "0.7.5"
indicatif = "0.16.2"
num-bigint = { version = "0.4", features = ["rand"] }